//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch2Go.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
    
    public partial class credit_card
    {
        public credit_card()
        {
            this.customer = new HashSet<customer>();
        }
        [Key][Column(Order = 0)]
        public int card_id { get; set; }
        [Key][Column(Order = 1)]
        public string card_type { get; set; }
    
        public virtual ICollection<customer> customer { get; set; }
    }
}
