//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch2Go.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class customer
    {
        public customer()
        {
            this.order = new HashSet<order>();
        }
        [Key]
        public int customer_id { get; set; }
        public int card_id { get; set; }
        public string password { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> phone_number { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<byte> email_notification { get; set; }
        public Nullable<byte> sms_notification { get; set; }
    
        public virtual credit_card credit_card { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
