//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch2Go.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class order
    {
        public order()
        {
            this.order_item = new HashSet<order_item>();
        }
        [Key]
        public int order_id { get; set; }
        public int customer_id { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal total_price { get; set; }
        public System.DateTime delivery_time { get; set; }
        public string delivery_region { get; set; }
        public string delivery_street { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<order_item> order_item { get; set; }
    }
}
