//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lunch2Go.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class product
    {
        public product()
        {
            this.order_item = new HashSet<order_item>();
        }
        [Key]
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public Nullable<decimal> price { get; set; }
        public string image { get; set; }
        public string unit_measure { get; set; }
        public string size { get; set; }
    
        public virtual ICollection<order_item> order_item { get; set; }
    }
}
